name: personal_card
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  simple_icons: ^10.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: PlaywriteGBS
      fonts:
        - asset: fonts/PlaywriteGBS-Regular.ttf

    - family: SourceSans3
      fonts:
        - asset: fonts/SourceSans3-ExtraLight.ttf