name: personal_card
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  simple_icons: ^10.1.3
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.14.1"
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: "ic_launcher"
  ios: false
  image_path: "images/icon.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "images/icon.png"
  adaptive_icon_foreground_inset: 30
  web:
    generate: true
    image_path: "images/icon.png"
    background_color: "#000000"
    theme_color: "#000000"
  

flutter:

  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: PlaywriteGBS
      fonts:
        - asset: fonts/PlaywriteGBS-Regular.ttf

    - family: SourceSans3
      fonts:
        - asset: fonts/SourceSans3-ExtraLight.ttf